name: Benchmark

on: [push]

jobs:
  Benchmark:
    name: Benchmark on node ${{ matrix.node_version }}
    uses: the-guild-org/shared-config/.github/workflows/ci-node-matrix.yml@main
    with:
      script: 'yarn build && yarn benchmark:basic'
      nodeVersions: '[18,20,22,23]'
