name: Canary Release

on:
  pull_request:
    branches:
      - master

jobs:
  publish-canary:
    name: Publish Canary
    runs-on: ubuntu-latest
    if: contains(github.actor, 'dependabot') == false
    steps:
      - name: Checkout Master
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node
        uses: actions/setup-node@v2
        with:
          node-version: 17
      - name: Configure Git Credentials
        run: |
          git config --global user.email "theguild-bot@users.noreply.github.com"
          git config --global user.name "theguild-bot"
          echo "machine github.com login theguild-bot password ${{secrets.GH_API_TOKEN}}" > ~/.netrc
      - name: Setup NPM credentials
        run: echo "//registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN" >> ~/.npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
      - uses: actions/cache@v2
        name: Cache node_modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-yarn-17-15-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-17-15
            ${{ runner.os }}-yarn-17
            ${{ runner.os }}-yarn-
      - name: Install Dependencies using Yarn
        run: yarn install --ignore-engines && git checkout yarn.lock
      - name: Release Canary
        id: canary
        uses: 'kamilkisiela/release-canary@master'
        if: github.repository == 'urigo/graphql-modules'
        with:
          npm-token: ${{ secrets.NODE_AUTH_TOKEN }}
          npm-script: 'yarn release:canary'
          changesets: true
      - name: Publish a message
        if: steps.canary.outputs.released
        uses: 'kamilkisiela/pr-comment@master'
        with:
          message: |
            The latest changes of this PR are available as alpha in npm (based on the declared `changesets`):

            ```
            ${{ steps.canary.outputs.changesetsPublishedPackages}}
            ```
          bot-token: ${{ secrets.GH_API_TOKEN }}
          bot: 'theguild-bot'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish a empty message
        if: steps.canary.outputs.released == 'false'
        uses: 'kamilkisiela/pr-comment@master'
        with:
          message: |
            The latest changes of this PR are not available as alpha, since there are no linked `changesets` for this PR.

                $ yarn pr

            Describe changes introduced in this Pull Request by running the above command.
          bot-token: ${{ secrets.GH_API_TOKEN }}
          bot: 'theguild-bot'
          github-token: ${{ secrets.GITHUB_TOKEN }}
